name: Builds for all os

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ windows-latest, macos-latest, ubuntu-latest ]
        toolchain: [ stable, nightly ]

    steps:
    - uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: cargo build --release --verbose
    - name: Upload Build
      uses: actions/upload-artifact@v3
      with:
        name: hideme_${{ matrix.os }}_rust-${{ matrix.toolchain }}_main-${{ github.sha }}
        path: target/release/hideme*
